### ISSUE TITLE
Movement Speed

### ISSUE THREAD

**Issue by 0CatDBlu113140** [bcmpinc/StardewHack#33]
https://smapi.io/log/d635636a2b9144a19e644dccd1d41329

First time reporting an issue. Here's the log SMAPI taught me how to get and then encouraged me to report on this site. I really like this mod and would like to use it, anyone know how to fix this?

**Comment by bcmpinc** [comment]
Hm, that's a versioning issue. I've uploaded a new version of StardewHack & Movement Speed. That should fix this bug.

**Comment by 0CatDBlu113140** [comment]
Thank you, I had updated everything else but movement speed apparently ( -.-) . I'm still getting used to SMAPI. I'm being extra careful this time around because I had messed up so bad before, I had to uninstall Stardew Valley and delete all the mods. There was missing features within the game, I don't even know how I did that.
